### ISSUE TITLE
Grid generated with origin element

### ISSUE THREAD

**Issue by SimplyPhy** [forsartis/figma-offgrid#1]
![grid demo](https://user-images.githubusercontent.com/7506223/73985362-f4920e00-4908-11ea-80bb-81ffb541cd36.gif)

It would be awesome if offgrid could generate the grid using the selected element as the first instance of the grid, as shown.

**Comment by forsartis** [comment]
Done! I kept the old behaviour when your selection is a component. In most cases you don’t want the master component as part of the grid, I guess.
