### ISSUE TITLE
Pre-selected input and Enter to create

### ISSUE THREAD

**Issue by SimplyPhy** [forsartis/figma-offgrid#2]
It would be great if, when initiating offgrid, if the first input box (rows) were active automatically, so you don't have to use your cursor to begin updating values.  The `tab` function allows for cursor-free navigation once one of the inputs is active.

Also, once the user is ready to generate the grid, it would be great if clicking `enter` served as a shortcut to generate the grid.  This would compliment the auto-active input functionality above.

**Comment by forsartis** [comment]
Thanks for the feedback! This should work now.
